### ISSUE TITLE
Mongoid

### ISSUE THREAD

**Issue by luizkowalski** [mirego/camaraderie#5]
Do this gem works with Mongoid or is it activerecord specific?

**Comment by remi** [comment]
Unfortunately it’s ActiveRecord-specific for the moment, since it’s the ORM we’re using here at @mirego. Although it would not be that hard to port it as its code is rather lightweight, it’s not in our plans right now.

Feel free to fork the project and hack it to make it work with Mongoid :smile:

**Comment by luizkowalski** [comment]
Thank you
